# Generated by Django 3.1.7 on 2021-03-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inStock',
            new_name='in_Stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='is_Active',
        ),
    ]
