# Generated by Django 3.1.7 on 2021-04-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210322_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
